import type { Service, Barber, Availability } from '@/types';

export const FALLBACK_SERVICES = [
  {
    id: 's1',
    name: 'Classic Haircut',
    nameAr: 'قص شعر كلاسيكي',
    price: 7,
    duration: 30,
    description: 'A precision haircut tailored to your style.',
    descriptionAr: 'قصة شعر دقيقة مصممة حسب ذوقك.',
    category: 'haircut',
    isActive: true,
    order: 1,
  },
  {
    id: 's2',
    name: 'Haircut & Beard',
    nameAr: 'قص شعر ولحية',
    price: 10,
    duration: 45,
    description: 'Complete grooming with a haircut and beard trim.',
    descriptionAr: 'عناية كاملة مع قص شعر وتشذيب لحية.',
    category: 'combo',
    isActive: true,
    order: 2,
  },
  {
    id: 's3',
    name: 'Beard Only',
    nameAr: 'لحية فقط',
    price: 4,
    duration: 20,
    description: 'Expert beard shaping and trimming.',
    descriptionAr: 'تشكيل وتشذيب لحية احترافي.',
    category: 'beard',
    isActive: true,
    order: 3,
  },
  {
    id: 's4',
    name: 'Master Combo',
    nameAr: 'الباقة الاحترافية',
    price: 15,
    duration: 60,
    description: 'Beard + Haircut + Hair Treatment — the full professional package.',
    descriptionAr: 'لحية + قص شعر + علاج شعر — الباقة الاحترافية الكاملة.',
    category: 'combo',
    isActive: true,
    order: 4,
  },
  {
    id: 's5',
    name: 'Ultimate Combo',
    nameAr: 'الباقة المتكاملة',
    price: 25,
    duration: 90,
    description: 'Beard + Haircut + Hair Treatment + Face Treatment — the ultimate experience.',
    descriptionAr: 'لحية + قص شعر + علاج شعر + علاج وجه — التجربة المتكاملة.',
    category: 'combo',
    isActive: true,
    order: 5,
  },
  {
    id: 's6',
    name: 'Face Treatment',
    nameAr: 'علاج الوجه',
    price: 12,
    duration: 40,
    description: 'Premium facial treatment for refreshed, glowing skin.',
    descriptionAr: 'علاج وجه فاخر لبشرة منتعشة ومشرقة.',
    category: 'treatment',
    isActive: true,
    order: 6,
  },
] as unknown as Service[];

export const FALLBACK_BARBERS = [
  { id: 'b1', name: 'Ahmad', nameAr: 'أحمد', isActive: true, order: 1 },
  { id: 'b2', name: 'Mohammad', nameAr: 'محمد', isActive: true, order: 2 },
  { id: 'b3', name: 'Omar', nameAr: 'عمر', isActive: true, order: 3 },
] as unknown as Barber[];

export const FALLBACK_AVAILABILITY = [
  { id: 'a0', dayOfWeek: 0, startTime: '09:00', endTime: '21:00', isActive: true, slotDuration: 30 },
  { id: 'a1', dayOfWeek: 1, startTime: '09:00', endTime: '21:00', isActive: true, slotDuration: 30 },
  { id: 'a2', dayOfWeek: 2, startTime: '09:00', endTime: '21:00', isActive: true, slotDuration: 30 },
  { id: 'a3', dayOfWeek: 3, startTime: '09:00', endTime: '21:00', isActive: true, slotDuration: 30 },
  { id: 'a4', dayOfWeek: 4, startTime: '09:00', endTime: '21:00', isActive: true, slotDuration: 30 },
  { id: 'a5', dayOfWeek: 5, startTime: '09:00', endTime: '21:00', isActive: false, slotDuration: 30 },
  { id: 'a6', dayOfWeek: 6, startTime: '10:00', endTime: '22:00', isActive: true, slotDuration: 30 },
] as unknown as Availability[];
